# Generated by Django 3.2 on 2022-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_userholidayinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userholidayinfo',
            name='day_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userholidayinfo',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
