# Generated by Django 3.2 on 2022-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_post_postlikedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikedislike',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='postlikedislike',
            name='is_like',
        ),
        migrations.AddField(
            model_name='postlikedislike',
            name='reaction',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='', max_length=20),
        ),
    ]
