# Generated by Django 3.2 on 2022-08-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_auto_20220820_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userholidayinfo',
            name='holiday_date',
        ),
    ]
