# Generated by Django 3.2 on 2022-08-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_auto_20220819_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
